### ISSUE TITLE
Cannot invoke "org.bukkit.command.CommandSender.getName()" because "chatEntity" is null

### ISSUE THREAD

**Issue by rudde0** [Emibergo02/RedisChat#15]
I don't know its happening when but there are lots of spam on the console. I can't reproduce this error in test environment.
```
[18:12:07 ERROR]: [io.lettuce.core.pubsub.PubSubEndpoint] Unexpected error occurred in RedisPubSubListener callback
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.getName()" because "chatEntity" is null
        at dev.unnm3d.redischat.chat.filters.FilterManager.filterMessage(FilterManager.java:85) ~[RedisChat-5.0-BETA3.jar:?]
        at dev.unnm3d.redischat.channels.ChannelManager.sendGenericChat(ChannelManager.java:297) ~[RedisChat-5.0-BETA3.jar:?]
        at dev.unnm3d.redischat.datamanagers.RedisDataManager.receiveMessage(RedisDataManager.java:67) ~[RedisChat-5.0-BETA3.jar:?]
        at dev.unnm3d.redischat.datamanagers.redistools.RedisAbstract$1.message(RedisAbstract.java:42) ~[RedisChat-5.0-BETA3.jar:?]
        at dev.unnm3d.redischat.datamanagers.redistools.RedisAbstract$1.message(RedisAbstract.java:39) ~[RedisChat-5.0-BETA3.jar:?]
        at io.lettuce.core.pubsub.PubSubEndpoint.notifyListeners(PubSubEndpoint.java:219) ~[?:?]
        at io.lettuce.core.pubsub.PubSubEndpoint.notifyMessage(PubSubEndpoint.java:208) ~[?:?]
        at io.lettuce.core.pubsub.PubSubCommandHandler.doNotifyMessage(PubSubCommandHandler.java:292) ~[?:?]
        at io.lettuce.core.pubsub.PubSubCommandHandler.notifyPushListeners(PubSubCommandHandler.java:223) ~[?:?]
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:647) ~[?:?]
        at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:112) ~[?:?]
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:599) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Emibergo02** [comment]
it is probably related to a error up in the log file. send the full log please

**Comment by Emibergo02** [comment]
send me the full log file please
